name: i1037
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked_services: ^1.5.0
  stacked: ^3.4.3

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  # stacked_generator: ^2.0.0-pre.1
  stacked_generator:
    path: ../../development/packages/generator

flutter:
  uses-material-design: true

